adding data model for legacy assembly table
EBI-Metagenomics/emgapi pull request #236
Opened 2021-11-17 13:01 UTC by mberacochea

2021-11-17 13:03 UTC, mberacochea commented
@caballero We need to add the migration too.

As the table was already created we need to run the migrate with " --fake"

2022-01-19 12:16 UTC, SandyRogers requested changes
This looks great, thank you. Could we just add one unit test to create a legacy assembly instance, and make sure that the redirect works? Has the potential to be accidentally broken in future otherwise 😁

2022-01-19 12:18 UTC, mberacochea commented
> This looks great, thank you. Could we just add one unit test to create a legacy assembly instance, and make sure that the redirect works? Has the potential to be accidentally broken in future otherwise grin

Definitely, thanks for the remainder

2022-01-19 16:59 UTC, caballero approved these changes

2022-01-27 13:22 UTC, merged